name: Quality Checks

on:
  push:
    branches:
      - main
      - development
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
      - development
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    env:
      TM_MOBILE_ENV: ${{ secrets.TM_MOBILE_ENV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Formatting
        run: npm run format

      - name: Run ESLint
        run: npm run lint

      - name: Check Types
        run: npm run check-types

      - name: Run Tests
        run: npm run test:final
